export const REWARDS_CATALOG = [
  {
    id: 'rew_zepto_1',
    brand: 'Zepto',
    title: '₹100 Off Perishables & Dairy',
    desc: 'Valid on quick-commerce grocery orders above ₹499',
    pointsCost: 150,
    code: 'FRESH100',
    category: 'Quick-Commerce',
    color: '#8B5CF6',
    icon: 'flash',
    affiliateUrl: 'https://zepto.onelink.me/freshkeep?af_c=zero_waste&promo=FRESH100',
  },
  {
    id: 'rew_swiggy_1',
    brand: 'Swiggy Instamart',
    title: '₹75 Off Fresh Produce',
    desc: 'Valid on fresh fruits & vegetables above ₹399',
    pointsCost: 120,
    code: 'GREENSAVE75',
    category: 'Quick-Commerce',
    color: '#F97316',
    icon: 'basket',
    affiliateUrl: 'https://swiggy.onelink.me/instamart?af_c=freshkeep&promo=GREENSAVE75',
  },
  {
    id: 'rew_zomato_1',
    brand: 'Zomato Healthy',
    title: '₹60 Off Guilt-Free Dining',
    desc: 'Valid on healthy restaurant orders above ₹299',
    pointsCost: 100,
    code: 'EATFRESH60',
    category: 'Food Delivery',
    color: '#EF4444',
    icon: 'restaurant',
    affiliateUrl: 'https://zomato.onelink.me/dining?af_c=freshkeep&promo=EATFRESH60',
  },
  {
    id: 'rew_blinkit_1',
    brand: 'Blinkit',
    title: 'Flat ₹50 Off Next Restock',
    desc: 'Applicable on pantry staples & milk',
    pointsCost: 80,
    code: 'RESTOCK50',
    category: 'Grocery',
    color: '#EAB308',
    icon: 'cart',
    affiliateUrl: 'https://blinkit.onelink.me/groceries?af_c=freshkeep&promo=RESTOCK50',
  },
  {
    id: 'rew_country_1',
    brand: 'Country Delight',
    title: 'Free 1L Organic Cow Milk',
    desc: 'Valid on fresh dairy subscription signup',
    pointsCost: 150,
    code: 'MILKSAVER',
    category: 'Dairy',
    color: '#3B82F6',
    icon: 'water',
    affiliateUrl: 'https://countrydelight.in/?ref=freshkeep&promo=MILKSAVER',
  },
  {
    id: 'rew_bare_1',
    brand: 'Bare Necessities',
    title: '20% Off Eco Kitchenware',
    desc: 'Reusable glass containers & silicone food wraps',
    pointsCost: 100,
    code: 'ECOFRESH20',
    category: 'Sustainability',
    color: '#10B981',
    icon: 'leaf',
    affiliateUrl: 'https://barenecessities.in/?ref=freshkeep&promo=ECOFRESH20',
  },
];
